apiVersion: v1
kind: ConfigMap
metadata:
  name: central-promos-enginee-config
  namespace: central-promos-enginee
data:
  NODE_ENV: "production"
  PORT: "3000"
  SERVICE_NAME: "central-promos-enginee"
  MERCADOLIBRE_API_BASE_URL: "https://api.meli.loquieroaca.com"
  PRICE_API_BASE_URL: "https://api.price.loquieroaca.com"
  CAMPAIGN_MLA_API_BASE_URL: "https://api.madre.loquieroaca.com"
  MERCADOLIBRE_API_TIMEOUT: "10000"
  PRICE_API_TIMEOUT: "10000"
  CAMPAIGN_MLA_API_TIMEOUT: "10000"
  SYNC_PROMOTION_TYPES: "PRE_NEGOTIATED,SMART"
  SYNC_PROMOTIONS_CRON: "0 0 17 * * *"
  ACTIVATE_PROMOTIONS_CRON: "0 0 10 * * *"
  DEACTIVATE_PROMOTIONS_CRON: "0 0 13 * * *"
  DEFAULT_MIN_PROFITABILITY: "0.12"
  DEFAULT_MIN_PROFIT: "0"
