apiVersion: v1
kind: Secret
metadata:
  name: central-promos-enginee-secrets
  namespace: central-promos-enginee
type: Opaque
stringData:
  MONGO_URL: "mongodb+srv://USER:PASSWORD@HOST/central-promos-enginee?tls=true&authSource=admin"
  MERCADOLIBRE_API_TOKEN: ""
  PRICE_API_TOKEN: ""
  CAMPAIGN_MLA_API_TOKEN: ""
