apiVersion: v1
kind: Secret
metadata:
  name: central-promos-enginee-secrets
  namespace: central-promos-enginee
type: Opaque
stringData:
  MONGO_URL: "mongodb+srv://central-promos-enginee:620eB871uF3x5tqo@central-promos-mongo-e9a90c6e.mongo.ondigitalocean.com/central-promos-enginee?tls=true&authSource=admin"
  MERCADOLIBRE_API_TOKEN: "sk_tlq_internal_prod_f3a9c2e8b41d7a09"
  PRICE_API_TOKEN: ""
